name: default

on:
  pull_request:
    branches:
      - master

jobs:
  ubuntu:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - run: date +%F > todays-date
    - name: Restore cache for today's nightly.
      uses: actions/cache@v1.0.0
      with:
        path: _neovim
        key: ${{ runner.os }}-nightly-${{ hashFiles('todays-date') }}
    - name: Setup from neovim nightly and run test
      run: |
        curl -OL https://raw.githubusercontent.com/norcalli/bot-ci/master/scripts/github-actions-setup.sh
        source github-actions-setup.sh nightly-x64
        make ci
    # - name: Test
      # run: make test
      # run: exec nvim -u NONE -E -R --headless +'set rtp+=$PWD' +'luafile scripts/docgen.lua' +q
  # macos:
  #   runs-on: [macos-latest]
  #   steps:
  #   - name: Checkout sources
  #     uses: actions/checkout@v2
  #   - name: Setup build dependencies
  #     run: |
  #       /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" &&
  #       brew install ninja libtool automake pkg-config gettext
  #   - name: Run test with building Nvim
  #     run: |
  #       make test
